---

weapons:
  - id: valderSpell
    rangeMin: 1
    rangeMax: 1
    canMoveAndAttack: true
    baseDamage:
      land: 1
    tagDamage:
      archer: 1.3
      soldier: 0.95
      villager: 0.95
      spearman: 0.65
      dog: 1.15
      wagon: 0.7
      knight: 0.55
      trebuchet: 0.55
      ballista: 0.6
      dragon: 0.3
      mage: 0.8
      giant: 0.4
      structure: 0.7
      balloon: 0.55
      harpy: 0.9
      witch: 0.7
      dragon: 0.35
      commander: 0.4
      
      warship: 0.55
      harpoonship: 0.45
      turtle: 0.55
      travelboat: 0.6
      merman: 0.95

unitClasses:
  - id: commander_valder
    name: unit_class_name_commander
    cost: 500
    movement: walking
    moveRange: 4
    aiPriority: 8.0
    regeneration: 5
    weapons:
      - id: valderSpell
#      - id: bow
        ammo: 5
    verbs:
      - load
      - capture
    tags:
      - commander
      - type.ground.light
    battleUnitCount: 1
    isCommander: true
    grooveId: raise_dead


units:
  - class: commander_valder
    faction: felheim
    name: character_valder_name
    mapAnimation: units/commanders/valder/map_valder
    battleAnimation: units/commanders/valder/battle_valder
    battleAnimationRiver: fx/river_overlay/battle_valder_river
    smallPortrait: units/commanders/valder/portrait_valder_small.png
    mediumPortrait: units/commanders/valder/portrait_valder_medium.png
    mapSpeed: 4.0
    skinColour: typeIV
    grabPos: [20, 26]
    deathMoveMin: 0
    deathMoveMax: 0
    stayAfterDeath: true
    sounds:
      attackMap: unitAttack
      attack: valder/valderAttack
      attackEffect: valder/valderAttackEffect
      captureShout: valder/valderCapture
      attackCommander: valder/valderCommanderKillAttack
      death: valder/valderDie
      deathMap: valder/valderDieGhost
      deathMapNoBattle: valder/valderDieNoBattle
      run: infantryLightMapEntry
      runMap: infantryLightMapEntry
      firstHit: valder/valderHit
      hit: hitOrganic
      hitMap: hitOrganic
      groove: valder/valderGrooveIntro
    attacks:
      - id: primary
        hitSpark: fx/bs_stab_attack
        hitDelay: 1.85
        effect: fx/bs_valder_attack
        effectDelay: 1.8
        ranged: true
    emotes:
      idle: idle
      negative: emote_negative
      laugh: emote_laugh
      surprise: emote_surprise
      hypno: emote_hypno
      bow: emote_bow
      dance: emote_dance
    shouts:
      valder_behold_the_gauntlet: valder/valderBeholdTheGauntlet
      valder_by_my_hand: valder/valderByMyHand
      valder_claim_this_power: valder/valderClaimThisPower
      valder_dead_outnumber: valder/valderDeadOutnumber
      valder_defeat: valder/valderNotTheEnd
      valder_felheim_rises: valder/valderFelheimRises
      valder_fooled: valder/valderFooled
      valder_goodbye: valder/valderGoodbye
      valder_hello: valder/valderHello
      valder_hmm: valder/valderHmm
      valder_hmph: valder/valderHmph
      valder_how_did_you: valder/valderHowDidYou
      valder_interesting: valder/valderInteresting
      valder_introduction: valder/valderIntroduction
      valder_laugh: valder/valderLaugh
      valder_no: valder/valderNo
      valder_no_escape: valder/valderNoEscape
      valder_nothing_personal: valder/valderNothingPersonal
      valder_oops: valder/valderOops
      valder_our_dominion: valder/valderOurDominion
      valder_pain1: valder/valderPain1
      valder_pain2: valder/valderPain2
      valder_pain3: valder/valderPain3
      valder_pain4: valder/valderPain4
      valder_perish: valder/valderPerish
      valder_ragna: valder/valderRagna
      valder_ragna_angry: valder/valderRagnaAngry
      valder_remember: valder/valderRemember
      valder_retribution: valder/valderRetribution
      valder_return_to_dust: valder/valderReturnToDust
      valder_rise: valder/valderRise
      valder_sigh: valder/valderSigh
      valder_sigrid: valder/valderSigrid
      valder_surprise: valder/valderSurprise
      valder_thanks: valder/valderThanks
      valder_this_fight: valder/valderThisFight
      valder_traitor: valder/valderTraitor
      valder_very_well: valder/valderVeryWell
      valder_victory: valder/valderVictory
      valder_what: valder/valderWhat
      valder_what_darkness: valder/valderWhatDarkness
      valder_will_not_fail: valder/valderWillNotFail
      valder_yes: valder/valderYes
      valder_you_fought_well: valder/valderYouFoughtWell
      valder_you_must_end_this: valder/valderYouMustEndThis
      valder_your_kingdom: valder/valderYourKingdom

    alternativeAttackSounds:
      no_voice: valder/valderAttackNoVoice

    hidden:
      shouts:
        - valder_pain3
      alternativeRuns:
        - angry_run
...
