---

weapons:
  - id: ragnaAttack
    rangeMin: 1
    rangeMax: 1
    canMoveAndAttack: true
    baseDamage:
      land: 1
    tagDamage:
      archer: 1.3
      soldier: 0.95
      villager: 0.95
      spearman: 0.65
      dog: 1.15
      wagon: 0.7
      knight: 0.55
      trebuchet: 0.55
      ballista: 0.6
      dragon: 0.3
      mage: 0.8
      giant: 0.4
      structure: 0.7
      balloon: 0.55
      harpy: 0.9
      witch: 0.7
      dragon: 0.35
      commander: 0.4
      
      warship: 0.55
      harpoonship: 0.45
      turtle: 0.55
      travelboat: 0.6
      merman: 0.95

unitClasses:
  - id: commander_ragna
    name: unit_class_name_commander
    cost: 500
    movement: walking
    moveRange: 4
    aiPriority: 8.0
    regeneration: 5
    weapons:
      - id: ragnaAttack
#      - id: bow
        ammo: 5
    verbs:
      - load
      - capture
    tags:
      - commander
      - type.ground.light
    battleUnitCount: 1
    isCommander: true
    grooveId: splash_jump


units:
  - class: commander_ragna
    faction: felheim
    name: character_ragna_name
    mapAnimation: units/commanders/ragna/map_ragna
    battleAnimation: units/commanders/ragna/battle_ragna
    battleAnimationRiver: fx/river_overlay/battle_ragna_river
    smallPortrait: units/commanders/ragna/portrait_ragna_small.png
    mediumPortrait: units/commanders/ragna/portrait_ragna_medium.png
    mapSpeed: 4.0
    skinColour: typeI
    grabPos: [26, 111]
    deathMoveMin: 0
    deathMoveMax: 0
    stayAfterDeath: true
    sounds:
      attackMap: unitAttack
      attack: ragna/ragnaAttack
      attackShout: ragna/ragnaPreAttack
      captureShout: ragna/ragnaCapture
      attackCommander: ragna/ragnaAttack
      attackCommanderShout: ragna/ragnaCommanderKillShout
      death: ragna/ragnaDie
      deathMap: ragna/ragnaDieGhost
      deathMapNoBattle: ragna/ragnaDieNoBattle
      run: infantryMediumMapEntry1
      runMap: infantryMediumMapEntry1
      firstHit: ragna/ragnaHit
      hit: hitOrganic
      hitMap: hitOrganic
      groove: ragna/ragnaGrooveIntro
    attacks:
      - id: primary
        hitSpark: fx/bs_stab_attack
        hitDelay: 0.3
    shouts:
      ragna_andstaydown: ragna/ragnaShoutAndStayDown
      ragna_attack1: ragna/ragnaShoutAttack1
      ragna_attack2: ragna/ragnaShoutAttack2
      ragna_attack3: ragna/ragnaShoutAttack3
      ragna_fightme1: ragna/ragnaShoutFightMe1
      ragna_fightme2: ragna/ragnaShoutFightMe2
      ragna_fightmemultiple: ragna/ragnaShoutFightMeMultiple
      ragna_getgood: ragna/ragnaShoutGetGood
      ragna_getouttamyway: ragna/ragnaShoutGetOuttaMyWay
      ragna_grr: ragna/ragnaShoutGrr
      ragna_hit1: ragna/ragnaShoutHit1
      ragna_hit2: ragna/ragnaShoutHit2
      ragna_hit3: ragna/ragnaShoutHit3
      ragna_hit4: ragna/ragnaShoutHit4
      ragna_hit5: ragna/ragnaShoutHit5
      ragna_hmph: ragna/ragnaShoutHmph
      ragna_how: ragna/ragnaShoutHow
      ragna_beatyouthistime: ragna/ragnaShoutIllBeatYouThisTime
      ragna_illcrushyou: ragna/ragnaShoutIllCrushYou
      ragna_tearyoutopieces: ragna/ragnaShoutIllTearYouToPieces
      ragna_imalreadydead: ragna/ragnaShoutImAlreadyDead
      ragna_imgonnabreakyou: ragna/ragnaShoutImGonnaBreakYou
      ragna_imunstoppable: ragna/ragnaShoutImUnstoppable
      ragna_introduction: ragna/ragnaShoutIntroduction
      ragna_itsme: ragna/ragnaShoutItsMe
      ragna_itsnotlike: ragna/ragnaShoutItsNotLike
      ragna_itsoverloser: ragna/ragnaShoutItsOverLoser
      ragna_iwon: ragna/ragnaShoutIWon
      ragna_iwonhah: ragna/ragnaShoutIWonHah
      ragna_laugh1: ragna/ragnaShoutLaugh1
      ragna_laugh2: ragna/ragnaShoutLaugh2
      ragna_laugh3: ragna/ragnaShoutLaugh3
      ragna_letsendthis: ragna/ragnaShoutLetsEndThis
      ragna_no: ragna/ragnaShoutNo
      ragna_noangry: ragna/ragnaShoutNoAngry
      ragna_oh1: ragna/ragnaShoutOh
      ragna_shutup: ragna/ragnaShoutShutUp
      ragna_sigh: ragna/ragnaShoutSigh
      ragna_specialmove: ragna/ragnaShoutSpecialMove
      ragna_stopthat: ragna/ragnaShoutStopThat
      ragna_sureokay: ragna/ragnaShoutSureOkay
      ragna_takethis: ragna/ragnaShoutTakeThis
      ragna_thanksiguess: ragna/ragnaShoutThanksIGuess
      ragna_thisisminenow: ragna/ragnaShoutThisIsMineNow
      ragna_thisisntfair: ragna/ragnaShoutThisIsntFair
      ragna_thisisntover: ragna/ragnaShoutThisIsntOver
      ragna_thissucks: ragna/ragnaShoutThisSucks
      ragna_ugh: ragna/ragnaShoutUgh
      ragna_ughfine1: ragna/ragnaShoutUghFine1
      ragna_ughfine2: ragna/ragnaShoutUghFine2
      ragna_whatangry: ragna/ragnaShoutWhatAngry
      ragna_whatshocked: ragna/ragnaShoutWhatShocked
      ragna_whatever: ragna/ragnaShoutWhatever
      ragna_whatsthematter: ragna/ragnaShoutWhatsTheMatter
      ragna_yeah: ragna/ragnaShoutYeah
      ragna_yourefinished: ragna/ragnaShoutYoureFinished
      ragna_youregonnaneedstitches: ragna/ragnaShoutYoureGonnaNeedStitches
      ragna_drowning: ragna/ragnaDrowning
    emotes:
      idle: idle
      surprise: emote_surprise
      positive: emote_positive
      negative: emote_negative
      laugh: emote_laugh
      idle_wet: idle_wet
      invisible: invisible
      shock: emote_shock
      tantrum: emote_tantrum
      pose: emote_pose
      thumbs_up: emote_thumbs_up
      dance: emote_dance
    alternativeRuns:
      - id: run_wet
        sound: infantryMediumWetMapEntry1

    alternativeAttackSounds:
      no_voice: ragna/ragnaAttackNoVoice

    hidden:
      emotes:
        - idle_wet
        - invisible
      shouts:
        - ragna_hit4
        - ragna_laugh2
        - ragna_ughfine1
        - ragna_drowning
        - ragna_fightmemultiple
      alternativeRuns:
        - run_wet
...
