---

weapons:
  - id: tenriAttack
    rangeMin: 1
    rangeMax: 1
    canMoveAndAttack: true
    baseDamage:
      land: 1
    tagDamage:
      archer: 1.3
      soldier: 0.95
      villager: 0.95
      spearman: 0.65
      dog: 1.15
      wagon: 0.7
      knight: 0.55
      trebuchet: 0.55
      ballista: 0.6
      dragon: 0.3
      mage: 0.8
      giant: 0.4
      structure: 0.7
      balloon: 0.55
      harpy: 0.9
      witch: 0.7
      dragon: 0.35
      commander: 0.4
      
      warship: 0.55
      harpoonship: 0.45
      turtle: 0.55
      travelboat: 0.6
      merman: 0.95

unitClasses:
  - id: commander_tenri
    name: unit_class_name_commander
    cost: 500
    movement: walking
    moveRange: 4
    aiPriority: 8.0
    regeneration: 5
    weapons:
      - id: tenriAttack
#      - id: bow
        ammo: 5
    verbs:
      - load
      - capture
    tags:
      - commander
      - type.ground.light
    battleUnitCount: 1
    isCommander: true
    grooveId: tornado

units:
  - class: commander_tenri
    faction: heavensong
    name: character_tenri_name
    mapAnimation: units/commanders/tenri/map_tenri
    battleAnimation: units/commanders/tenri/battle_tenri
    battleAnimationRiver: fx/river_overlay/battle_tenri_river
    smallPortrait: units/commanders/tenri/portrait_tenri_small.png
    mediumPortrait: units/commanders/tenri/portrait_tenri_medium.png
    mapSpeed: 4.0
    skinColour: typeIII
    grabPos: [30, 28]
    deathMoveMin: 0
    deathMoveMax: 0
    sounds:
      attackMap: unitAttack
      preAttack: tenri/tenriPreAttack
      attack: tenri/tenriAttack
      attackShout: tenri/tenriAttackShout
      captureShout: tenri/tenriShoutTheresNoTimeToWaste
      attackCommanderShout: tenri/tenriCommanderKillShout
      death: tenri/tenriDie
      deathMap: tenri/tenriDieGhost
      deathMapNoBattle: tenri/tenriDieNoBattle
      run: infantryLightMapEntry
      runMap: infantryLightMapEntry
      firstHit: tenri/tenriHit
      hit: hitOrganic
      hitMap: hitOrganic
      groove: tenri/tenriGrooveIntro
    attacks:
      - id: primary
        hitSpark: fx/bs_stab_attack
        hitDelay: 1.5
    emotes:
      idle: idle
      surprise: emote_surprise
      positive: emote_positive
      negative: emote_negative
      laugh: emote_laugh
      calm: emote_calm
      bow: emote_bow
      dance: emote_dance
    shouts:
      tenri_acoldwindblows: tenri/tenriShoutAColdWindBlows
      tenri_astormapproaches: tenri/tenriShoutAStormApproaches
      tenri_attack1: tenri/tenriShoutAttack1
      tenri_attack2: tenri/tenriShoutAttack2
      tenri_attack3: tenri/tenriShoutAttack3
      tenri_attack4: tenri/tenriShoutAttack4
      tenri_ihavefailed: tenri/tenriShoutIHaveFailed
      tenri_imnotheretoplay: tenri/tenriShoutImNotHereToPlay
      tenri_hit1: tenri/tenriShoutHit1
      tenri_hit2: tenri/tenriShoutHit2
      tenri_hit3: tenri/tenriShoutHit3
      tenri_powerofthetempest: tenri/tenriShoutPowerOfTheTempest
      tenri_theresnotimetowaste: tenri/tenriShoutTheresNoTimeToWaste
      tenri_thewindrises: tenri/tenriShoutTheWindRises
      tenri_illmakethisquick: tenri/tenriShoutIllMakeThisQuick
      tenri_absolutelynot: tenri/tenriShoutAbsolutelyNot
      tenri_agreed: tenri/tenriShoutAgreed
      tenri_fallback: tenri/tenriShoutFallBack
      tenri_farewell: tenri/tenriShoutFarewell
      tenri_getoutofmysight: tenri/tenriShoutGetOutOfMySight
      tenri_greetings: tenri/tenriShoutGreetings
      tenri_hmph: tenri/tenriShoutHmph
      tenri_howtimeflies: tenri/tenriShoutHowTimeFlies
      tenri_itireofyourpresence: tenri/tenriShoutITireOfYourPresence
      tenri_koji1: tenri/tenriShoutKoji1
      tenri_koji2: tenri/tenriShoutKoji2
      tenri_laugh1: tenri/tenriShoutLaugh1
      tenri_laugh2: tenri/tenriShoutLaugh2
      tenri_no: tenri/tenriShoutNo
      tenri_noonethreatensmypeople: tenri/tenriShoutNoOneThreatensMyPeople
      tenri_sigh: tenri/tenriShoutSigh
      tenri_standdown: tenri/tenriShoutStandDown
      tenri_stopthis: tenri/tenriShoutStopThis
      tenri_victoryshallbeswift: tenri/tenriShoutVictoryShallBeSwift
      tenri_weareoldfriends: tenri/tenriShoutWeAreOldFriends
      tenri_westandtogether: tenri/tenriShoutWeStandTogether
      tenri_whatisthis1: tenri/tenriShoutWhatIsThis1
      tenri_whatisthis2: tenri/tenriShoutWhatIsThis2
      tenri_yes: tenri/tenriShoutYes
      tenri_youfiend: tenri/tenriShoutYouFiend
      tenri_youhavemythanks: tenri/tenriShoutYouHaveMyThanks
      tenri_youthinkthisisagame: tenri/tenriShoutYouThinkThisIsAGame

    alternativeAttackSounds:
      no_voice: tenri/tenriAttackNoVoice

    hidden:
      shouts:
        - tenri_attack1
        - tenri_whatisthis2

...
