---

weapons:
  - id: sedgeAttack
    rangeMin: 1
    rangeMax: 1
    canMoveAndAttack: true
    baseDamage:
      land: 1
    tagDamage:
      archer: 1.3
      soldier: 0.95
      villager: 0.95
      spearman: 0.65
      dog: 1.15
      wagon: 0.7
      knight: 0.55
      trebuchet: 0.55
      ballista: 0.6
      dragon: 0.3
      mage: 0.8
      giant: 0.4
      structure: 0.7
      balloon: 0.55
      harpy: 0.9
      witch: 0.7
      dragon: 0.35
      commander: 0.4
      
      warship: 0.55
      harpoonship: 0.45
      turtle: 0.55
      travelboat: 0.6
      merman: 0.95

unitClasses:
  - id: commander_sedge
    name: unit_class_name_commander
    cost: 500
    movement: walking
    moveRange: 4
    aiPriority: 8.0
    regeneration: 5
    weapons:
      - id: sedgeAttack
#      - id: bow
        ammo: 5
    verbs:
      - load
      - capture
    tags:
      - commander
      - type.ground.light
    battleUnitCount: 1
    isCommander: true
    grooveId: sadistic_rush

units:
  - class: commander_sedge
    faction: floran
    name: character_sedge_name
    mapAnimation: units/commanders/sedge/map_sedge
    battleAnimation: units/commanders/sedge/battle_sedge
    battleAnimationRiver: fx/river_overlay/battle_sedge_river
    smallPortrait: units/commanders/sedge/portrait_sedge_small.png
    mediumPortrait: units/commanders/sedge/portrait_sedge_medium.png
    mapSpeed: 4.0
    grabPos: [36, 62]
    deathMoveMin: 0
    deathMoveMax: 0
    attackRunTimeMin: 0
    attackRunTimeMax: 0
    sounds:
      attackMap: unitAttack
      attack: sedge/sedgeAttack
      attackBuilding: sedge/sedgeAttackBuilding
      preAttack: sedge/sedgePreAttack
      captureShout: sedge/sedgeShoutAllBelongs
      attackCommander: sedge/sedgeCommanderKillAttack
      death: sedge/sedgeDie
      deathMap: sedge/sedgeDieGhost
      deathMapNoBattle: sedge/sedgeDieNoBattle
      run: infantryLightMapEntry
      runMap: infantryLightMapEntry
      firstHit: sedge/sedgeHit
      hit: hitOrganic
      hitMap: hitOrganic
      groove: sedge/sedgeGrooveIntro  
    attacks:
      - id: secondary
        hitSpark: fx/bs_stab_attack
        hitDelay: 0.6
        samePanel: true
      - id: attackBuilding
        attackAnimationSequence: attack_building
        hitSpark: fx/bs_stab_attack
        hitDelay: 0.8
        againstBuilding: true
        attackSound: attackBuilding
      - id: primary
        hitSpark: fx/bs_stab_attack
        hitDelay: 0.6
    emotes:
      idle: idle
      surprise: emote_surprise
      positive: emote_positive
      negative: emote_negative
      laugh: emote_laugh
      dying: emote_dying
      dead: emote_dead
      dance: emote_dance
    shouts:
      sedge_attackgloat1: sedge/sedgeShoutAttackGloat1
      sedge_attackgloat2: sedge/sedgeShoutAttackGloat2
      sedge_blades: sedge/sedgeShoutBlades
      sedge_capture: sedge/sedgeShoutAllBelongs
      sedge_die: sedge/sedgeShoutTheHuntEnds
      sedge_hit1: sedge/sedgeShoutHit1
      sedge_hit2: sedge/sedgeShoutHit2
      sedge_hit3: sedge/sedgeShoutHit3
      sedge_select: sedge/sedgeShoutTheHuntBegins
      sedge_attack1: sedge/sedgeShoutAttack1
      sedge_attack2: sedge/sedgeShoutAttack2
      sedge_attack3: sedge/sedgeShoutAttack3
      sedge_alwayswins: sedge/sedgeShoutAlwaysWins
      sedge_doesntteleport: sedge/sedgeShoutDoesntTeleport
      sedge_flyaway: sedge/sedgeShoutFlyAway
      sedge_freshprey: sedge/sedgeShoutFreshPrey
      sedge_goodbye: sedge/sedgeShoutGoodbye
      sedge_hellofriends: sedge/sedgeShoutHelloFriends
      sedge_hiss: sedge/sedgeShoutHiss
      sedge_hmph1: sedge/sedgeShoutHmph1
      sedge_hmph2: sedge/sedgeShoutHmph2
      sedge_hungers: sedge/sedgeShoutHungers
      sedge_laugh1: sedge/sedgeShoutLaugh1
      sedge_laugh2: sedge/sedgeShoutLaugh2
      sedge_laugh3: sedge/sedgeShoutLaugh3
      sedge_look: sedge/sedgeShoutLook
      sedge_neverloses: sedge/sedgeShoutNeverLoses
      sedge_no: sedge/sedgeShoutNo
      sedge_oops: sedge/sedgeShoutOops
      sedge_sigh: sedge/sedgeShoutSigh
      sedge_sighcontented: sedge/sedgeShoutSighContented
      sedge_thanks: sedge/sedgeShoutThanks
      sedge_thehunt: sedge/sedgeShoutTheHunt
      sedge_thiswasfun: sedge/sedgeShoutThisWasFun
      sedge_timetorun: sedge/sedgeShoutTimeToRun
      sedge_trespassers: sedge/sedgeShoutTrespassers
      sedge_watchyourstep: sedge/sedgeShoutWatchYourStep
      sedge_what: sedge/sedgeShoutWhat
      sedge_willbeeasy: sedge/sedgeShoutWillBeEasy
      sedge_willcatchyou: sedge/sedgeShoutWillCatchYou
      sedge_yes: sedge/sedgeShoutYes
      sedge_youllregretthis: sedge/sedgeShoutYoullRegretThis
      sedge_youlltastegood: sedge/sedgeShoutYoullTasteGood
      sedge_yousmellgood: sedge/sedgeShoutYouSmellGood

    alternativeAttackSounds:
      no_voice: sedge/sedgeAttackNoVoice

    hidden:
      emotes:
        - dead
        - dying
      shouts:
        - sedge_blades
      alternativeRuns:
        - angry_run
...
