---

weapons:
  - id: ryotaAttack
    rangeMin: 1
    rangeMax: 1
    canMoveAndAttack: true
    baseDamage:
      land: 1
    tagDamage:
      archer: 1.3
      soldier: 0.95
      villager: 0.95
      spearman: 0.65
      dog: 1.15
      wagon: 0.7
      knight: 0.55
      trebuchet: 0.55
      ballista: 0.6
      dragon: 0.3
      mage: 0.8
      giant: 0.4
      structure: 0.7
      balloon: 0.55
      harpy: 0.9
      witch: 0.7
      dragon: 0.35
      commander: 0.4
      
      warship: 0.55
      harpoonship: 0.45
      turtle: 0.55
      travelboat: 0.6
      merman: 0.95

unitClasses:
  - id: commander_ryota
    name: unit_class_name_commander
    cost: 500
    movement: walking
    moveRange: 4
    aiPriority: 8.0
    regeneration: 5
    weapons:
      - id: ryotaAttack
#      - id: bow
        ammo: 5
    verbs:
      - load
      - capture
    tags:
      - commander
      - type.ground.light
    battleUnitCount: 1
    isCommander: true
    grooveId: dash

units:
  - class: commander_ryota
    faction: heavensong
    name: character_ryota_name
    mapAnimation: units/commanders/ryota/map_ryota
    battleAnimation: units/commanders/ryota/battle_ryota
    battleAnimationRiver: fx/river_overlay/battle_ryota_river
    smallPortrait: units/commanders/ryota/portrait_ryota_small.png
    mediumPortrait: units/commanders/ryota/portrait_ryota_medium.png
    mapSpeed: 4.0
    skinColour: typeIII
    grabPos: [28, 27]
    deathMoveMin: 0
    deathMoveMax: 0
    sounds:
      attackMap: unitAttack
      attack: ryota/ryotaAttack
      attackShout: ryota/ryotaAttackShout
      captureShout: ryota/ryotaCapture
      attackCommanderShout: ryota/ryotaCommanderKillShout
      death: ryota/ryotaDie
      deathMap: ryota/ryotaDieGhost
      deathMapNoBattle: ryota/ryotaDieNoBattle
      run: ryota/ryotaEntry
      runMap: ryota/ryotaEntry
      firstHit: ryota/ryotaHit
      hit: hitOrganic
      hitMap: hitOrganic
      groove: ryota/ryotaGrooveIntro
    attacks:
      - id: primary
        hitSpark: fx/bs_stab_attack
        hitDelay: 1.55
    emotes:
      idle: idle
      surprise: emote_surprise
      positive: emote_positive
      negative: emote_negative
      laugh: emote_laugh
      blush: emote_blush
      dance: emote_dance
    shouts:
      ryota_attack1: ryota/ryotaShoutAttack1
      ryota_attack2: ryota/ryotaShoutAttack2
      ryota_attack3: ryota/ryotaShoutAttack3
      ryota_attack4: ryota/ryotaShoutAttack4
      ryota_attack5: ryota/ryotaShoutAttack5
      ryota_attack6: ryota/ryotaShoutAttack6
      ryota_attack7: ryota/ryotaShoutAttack7
      ryota_attack8: ryota/ryotaShoutAttack8
      ryota_drawyourfinalbreath: ryota/ryotaShoutDrawYourFinalBreath
      ryota_empress: ryota/ryotaShoutEmpress
      ryota_farewell: ryota/ryotaShoutFarewell
      ryota_goodriddance: ryota/ryotaShoutGoodRiddance
      ryota_greetings: ryota/ryotaShoutGreetings
      ryota_hit1: ryota/ryotaShoutHit1
      ryota_hit2: ryota/ryotaShoutHit2
      ryota_hit3: ryota/ryotaShoutHit3
      ryota_hit4: ryota/ryotaShoutHit4
      ryota_hit5: ryota/ryotaShoutHit5
      ryota_hmph1: ryota/ryotaShoutHmph1
      ryota_hmph2: ryota/ryotaShoutHmph2
      ryota_howunexpected: ryota/ryotaShoutHowUnexpected
      ryota_ihavefailed: ryota/ryotaShoutIHaveFailed
      ryota_illcutyoudown: ryota/ryotaShoutIllCutYouDown
      ryota_ishalldefendyou: ryota/ryotaShoutIShallDefendYou
      ryota_ishallfightuntilifall: ryota/ryotaShoutIShallFightUntilIFall
      ryota_ishalltakethis: ryota/ryotaShoutIShallTakeThis
      ryota_iwillnotbedefeated: ryota/ryotaShoutIWillNotBeDefeated
      ryota_laugh1: ryota/ryotaShoutLaugh1
      ryota_laugh2: ryota/ryotaShoutLaugh2
      ryota_myempress: ryota/ryotaShoutMyEmpress
      ryota_no: ryota/ryotaShoutNo
      ryota_oops: ryota/ryotaShoutOops
      ryota_pleaseforgiveme: ryota/ryotaShoutPleaseForgiveMe
      ryota_sedge: ryota/ryotaShoutSedge
      ryota_sigh: ryota/ryotaShoutSigh
      ryota_somedayimaybeworthy: ryota/ryotaShoutSomeDayIMayBeWorthy
      ryota_stepback: ryota/ryotaShoutStepBack
      ryota_thankyou: ryota/ryotaShoutThankYou
      ryota_thebeautifulqueenmercia: ryota/ryotaShoutTheBeautifulQueenMercia
      ryota_theywontseemecoming: ryota/ryotaShoutTheyWontSeeMeComing
      ryota_victorydrawscloser: ryota/ryotaShoutVictoryDrawsCloser
      ryota_what: ryota/ryotaShoutWhat
      ryota_willnotbedefeated: ryota/ryotaShoutWillNotBeDefeated
      ryota_yes: ryota/ryotaShoutYes
      ryota_you: ryota/ryotaShoutYou
      ryota_youarealreadydead: ryota/ryotaShoutYouAreAlreadyDead
      ryota_youhavebeencareless: ryota/ryotaShoutYouHaveBeenCareless
      ryota_youllneverseemecoming: ryota/ryotaShoutYoullNeverSeeMeComing
      ryota_youreamonster: ryota/ryotaShoutYoureAMonster
      ryota_yourecornered: ryota/ryotaShoutYoureCornered

    alternativeAttackSounds:
      no_voice: ryota/ryotaAttackNoVoice

    hidden:
      shouts:
        - ryota_attack4
        - ryota_hit4
        - ryota_hit5

...
