---

weapons:
  - id: elodieCello
    rangeMin: 1
    rangeMax: 1
    canMoveAndAttack: true
    baseDamage:
      land: 1
    tagDamage:
      archer: 1.3
      soldier: 0.95
      villager: 0.95
      spearman: 0.65
      dog: 1.15
      wagon: 0.7
      knight: 0.55
      trebuchet: 0.55
      ballista: 0.6
      dragon: 0.3
      mage: 0.8
      giant: 0.4
      structure: 0.7
      balloon: 0.55
      harpy: 0.9
      witch: 0.7
      dragon: 0.35
      commander: 0.4
      
      warship: 0.55
      harpoonship: 0.45
      turtle: 0.55
      travelboat: 0.6
      merman: 0.95

unitClasses:
  - id: commander_elodie
    name: unit_class_name_commander
    cost: 500
    movement: walking
    moveRange: 4
    aiPriority: 8.0
    regeneration: 5
    weapons:
      - id: elodieCello
#      - id: bow
        ammo: 5
    verbs:
      - load
      - capture
    tags:
      - commander
      - type.ground.light
    battleUnitCount: 1
    isCommander: true
    grooveId: convert


units:
  - class: commander_elodie
    faction: guardian
    name: character_elodie_name
    mapAnimation: units/commanders/elodie/map_elodie
    battleAnimation: units/commanders/elodie/battle_elodie
    battleAnimationRiver: fx/river_overlay/battle_elodie_river
    smallPortrait: units/commanders/elodie/portrait_elodie_small.png
    mediumPortrait: units/commanders/elodie/portrait_elodie_medium.png
    mapSpeed: 4.0
    deathMoveMin: 0
    deathMoveMax: 0
    skinColour: typeIV
    grabPos: [38, 36]
    stayAfterDeath: true
    sounds:
      attackMap: unitAttack
      attack: elodie/elodieAttack
      attackEffect: elodie/elodieAttackEffect
      captureShout: elodie/elodieCapture
      attackCommander: elodie/elodieCommanderKillAttack
      death: elodie/elodieDie
      deathMap: elodie/elodieDieGhost
      deathMapNoBattle: elodie/elodieDieNoBattle
      run: balloonEntry
      runMap: balloonEntryMap
      firstHit: elodie/elodieHit
      hit: hitOrganic
      hitMap: hitOrganic
      groove: elodie/elodieGrooveIntro
    attacks:
      - id: closeRange
        hitSpark: fx/bs_stab_attack
        effect: fx/bs_elodie_attack_2
        effectPaletteSwaps: true
        effectDelay: 2.0
        hitDelay: 2.0
        samePanel: true
      - id: primary
        hitSpark: fx/bs_stab_attack
        effect: fx/bs_elodie_attack
        effectPaletteSwaps: true
        effectDelay: 2.0
        hitDelay: 2.1
        ranged: true
    emotes:
      idle: idle
      play: emote_play
      positive: emote_positive
      negative: emote_negative
      requiem_1: emote_requiem_1
      requiem_2: emote_requiem_2
      requiem_3: emote_requiem_3
      requiem_4: emote_requiem_4
      human_1: emote_human_1
      human_2: emote_human_2
      dance: emote_dance
    shouts:
      elodie_amifree: elodie/elodieShoutAmIFree
      elodie_anecessarymove: elodie/elodieShoutANecessaryMove
      elodie_enteroblivion: elodie/elodieShoutEnterOblivion
      elodie_farewell: elodie/elodieShoutFarewell
      elodie_fatesworsethandeath: elodie/elodieShoutFatesWorseThanDeath
      elodie_greetings: elodie/elodieShoutGreetings
      elodie_hearmysong: elodie/elodieShoutHearMySong
      elodie_hit1: elodie/elodieShoutHit1
      elodie_hit2: elodie/elodieShoutHit2
      elodie_hit3: elodie/elodieShoutHit3
      elodie_hit4: elodie/elodieShoutHit4
      elodie_hmm: elodie/elodieShoutHmm
      elodie_hmph: elodie/elodieShoutHmph
      elodie_iamsorry: elodie/elodieShoutIAmSorry
      elodie_icannotallowthis: elodie/elodieShoutICannotAllowThis
      elodie_iclaimyourheart: elodie/elodieShoutIClaimYourHeart
      elodie_idowhatimust: elodie/elodieShoutIDoWhatIMust
      elodie_introduction: elodie/elodieShoutIntroduction
      elodie_isitover: elodie/elodieShoutIsItOver
      elodie_isthereanotherway: elodie/elodieShoutIsThereAnotherWay
      elodie_itisnotso: elodie/elodieShoutItIsNotSo
      elodie_itmustbethisway: elodie/elodieShoutItMustBeThisWay
      elodie_laugh1: elodie/elodieShoutLaugh1
      elodie_laugh2: elodie/elodieShoutLaugh2
      elodie_liar: elodie/elodieShoutLiar
      elodie_myduty: elodie/elodieShoutMyDuty
      elodie_no: elodie/elodieShoutNo
      elodie_nodesperate: elodie/elodieShoutNoDesperate
      elodie_requiem: elodie/elodieShoutRequiem
      elodie_ishallplayyouasong: elodie/elodieShoutShallIPlayYouASong
      elodie_sigh: elodie/elodieShoutSigh
      elodie_silencefalls: elodie/elodieShoutSilenceFalls
      elodie_thankyou: elodie/elodieShoutThankYou
      elodie_thedarkness: elodie/elodieShoutTheDarkness
      elodie_thisismyburden: elodie/elodieShoutThisIsMyBurden
      elodie_thisisyourswansong: elodie/elodieShoutThisIsYourSwanSong
      elodie_verywell: elodie/elodieShoutVeryWell
      elodie_what: elodie/elodieShoutWhat
      elodie_yes: elodie/elodieShoutYes
      elodie_yourheartisweak: elodie/elodieShoutYourHeartIsWeak
      elodie_youwontstopme: elodie/elodieShoutYouWontStopMe

    alternativeAttackSounds:
      no_voice: elodie/elodieAttackNoVoice

    hidden:
      emotes:
        - requiem_3
        - requiem_4
        - positive
...
