---

weapons:
  - id: kojiAttack
    rangeMin: 1
    rangeMax: 1
    canMoveAndAttack: true
    baseDamage:
      land: 1
    tagDamage:
      archer: 1.3
      soldier: 0.95
      villager: 0.95
      spearman: 0.65
      dog: 1.15
      wagon: 0.7
      knight: 0.55
      trebuchet: 0.55
      ballista: 0.6
      dragon: 0.3
      mage: 0.8
      giant: 0.4
      structure: 0.7
      balloon: 0.55
      harpy: 0.9
      witch: 0.7
      dragon: 0.35
      commander: 0.4
      
      warship: 0.55
      harpoonship: 0.45
      turtle: 0.55
      travelboat: 0.6
      merman: 0.95

unitClasses:
  - id: commander_koji
    name: unit_class_name_commander
    cost: 500
    movement: walking
    moveRange: 4
    aiPriority: 8.0
    regeneration: 5
    weapons:
      - id: kojiAttack
#      - id: bow
        ammo: 5
    verbs:
      - load
      - capture
    tags:
      - commander
      - type.ground.light
      - tall
    battleUnitCount: 1
    isCommander: true
    grooveId: drone_bombs

units:
  - class: commander_koji
    faction: heavensong
    name: character_koji_name
    mapAnimation: units/commanders/koji/map_koji
    battleAnimation: units/commanders/koji/battle_koji
    battleAnimationRiver: fx/river_overlay/battle_koji_river
    smallPortrait: units/commanders/koji/portrait_koji_small.png
    mediumPortrait: units/commanders/koji/portrait_koji_medium.png
    mapSpeed: 4.0
    skinColour: typeIII
    grabPos: [29, 39]
    deathMoveMin: 0
    deathMoveMax: 0
    alternativeCapture:
      endPosOffset: -160 #coming from the left
    sounds:
      attackMap: unitAttack
      attack: koji/kojiAttack
      attackShout: koji/kojiPreAttack
      captureShout: koji/kojiCapture
      attackCommanderShout: koji/kojiCommanderKillShout
      capture: koji/kojiCaptureCrash
      death: koji/kojiDie
      deathMap: koji/kojiDieGhost
      deathMapNoBattle: koji/kojiDieNoBattle
      run: giantEntry
      runMap: giantEntry
      firstHit: koji/kojiHit
      hit: hitWood
      hitMap: hitWood
      groove: koji/kojiGrooveIntro
    attacks:
      - id: primary
        hitSpark: fx/bs_stab_attack
        hitDelay: 2.65
    shouts:
      koji_attack1: koji/kojiShoutAttack1
      koji_attack2: koji/kojiShoutAttack2
      koji_attack3: koji/kojiShoutAttack3
      koji_attack4: koji/kojiShoutAttack4
      koji_capture1: koji/kojiShoutHopeICanFit
      koji_capture2: koji/kojiShoutAnyoneHome
      koji_die: koji/kojiShoutSorryMum
      koji_yeah: koji/kojiShoutYeah1
      koji_groovecheer1: koji/kojiShoutYeah2
      koji_groovecheer2: koji/kojiShoutHaha
      koji_groove: koji/kojiShoutSparrowBombs
      koji_hey: koji/kojiShoutHey
      koji_hit1: koji/kojiShoutHit1
      koji_hit2: koji/kojiShoutHit2
      koji_hit3: koji/kojiShoutHit3
      koji_hit4: koji/kojiShoutHit4
      koji_hit5: koji/kojiShoutHit5
      koji_imrealsorry: koji/kojiShoutImRealSorry
      koji_ivemessedup: koji/kojiShoutIveMessedUp
      koji_iwon: koji/kojiShoutIWon
      koji_iwonawesome: koji/kojiShoutIWonAwesome
      koji_preattack1: koji/kojiShoutIaidoStance
      koji_preattack2: koji/kojiShoutLetsGoTenko
      koji_preattack3: koji/kojiShoutBattleStanceActivate
      koji_select1: koji/kojiShoutThisIsMyChance
      koji_select2: koji/kojiShoutThisWillBeAwesome
      koji_imadeitmyself: koji/kojiShoutIMadeItMyself
      koji_introdution: koji/kojiShoutIntroduction
      koji_letshopethisworks: koji/kojiShoutLetsHopeThisWorks
      koji_seeya: koji/kojiShoutSeeYa
      koji_thefinishingblow: koji/kojiShoutTheFinishingBlow
      koji_thisismypuppettenko: koji/kojiShoutThisIsMyPuppetTenko
      koji_thiswillbefun: koji/kojiShoutThisWillBeFun
      koji_waah: koji/kojiShoutWaah
      koji_youunderestimatedme: koji/kojiShoutYouUnderestimatedMe
      koji_heyangry: koji/kojiShoutHeyAngry
      koji_imtougherthanyouthink: koji/kojiShoutImTougherThanYouThink
      koji_laugh1: koji/kojiShoutLaugh1
      koji_laugh2: koji/kojiShoutLaugh2
      koji_naw: koji/kojiShoutNaw
      koji_oops: koji/kojiShoutOops
      koji_sigh: koji/kojiShoutSigh
      koji_tenkoisdueforanupgrade: koji/kojiShoutTenkoIsDueForAnUpgrade
      koji_thanks: koji/kojiShoutThanks
      koji_uh: koji/kojiShoutUh
      koji_wha: koji/kojiShoutWha
      koji_wow: koji/kojiShoutWow
      koji_hmph: koji/kojiShoutHmph
      koji_youshouldntthreatenme: koji/kojiShoutYouShouldntThreatenMe

    emotes:
      idle: idle
      surprise: emote_surprise
      positive: emote_positive
      negative: emote_negative
      hypno: emote_hypno
      mech: emote_mech
      bow: emote_bow
      dance: emote_dance
    alternativeRuns:
      - id: emote_mech
        sound: trebuchetMapEntry

    alternativeAttackSounds:
      no_voice: koji/kojiAttackNoVoice
      
    hidden:
      emotes:
        - mech

      alternativeRuns:
        - emote_mech
...
