---

unitClasses:
  - id: giant_upgrade
    name: unit_class_name_giant
    cost: 200
    movement: walking
    moveRange: 3
    damageMultiplier: 0
    canBeReinforced: false
    isStructure: false
    classIconSpritesheet: ui_AgeOfWarGrooveMod
    aiPriority: 0
    weapons: []
    verbs:
      - load
    tags: []
    hostileNeutral: true
    isRecruitable: true
    palettePriority: 1
    isSpawnable: false
    isHidden: true
    grooveId: upgraded_indicator
      
units:
  - class: giant_upgrade
    faction: neutral
    name: unit_class_name_giant_cherrystone
    mapAnimation: units/giant/cherrystone/map_giant_cherrystone
    smallPortrait: units/giant/cherrystone/portrait_giant_cherrystone_small.png
    mediumPortrait: units/giant/cherrystone/portrait_giant_cherrystone_medium.png
    mapSpeed: 4.0
    grabPos: [13, 14]
    sounds:
      death: soldierDieRed
      deathMap: unitDie
      run: infantryLightEntry
      runMap: infantryLightMapEntry
      hit: hitOrganic
      hitMap: hitOrganic

...