---

verbs:
  - id: build
    icon: ui/icons/unit_action_icon_build.png
    name: ui_unit_verbs_build
    targetColour: target
    targetOutlineColour: target_outline
    preExecute: true
    scriptName: verbs/build
    aiUses: true
  - id: build_phase_two
    icon: ui/icons/unit_action_icon_build.png
    name: ui_unit_verbs_build_phase_two
    targetColour: target
    targetOutlineColour: target_outline
    targetted: true
    directTarget: true
    scriptName: verbs/build_phase_two
    aiUses: true
  - id: salvage
    icon: ui/icons/unit_action_icon_salvage.png
    name: ui_unit_verbs_salvage
    targetColour: target
    targetOutlineColour: target_outline
    targetted: true
    scriptName: verbs/salvage
    aiUses: true
  - id: buy_artifacts
    icon: ui/icons/unit_action_icon_recruit.png
    name: ui_unit_verbs_buy_artifacts
    targetColour: target
    targetOutlineColour: target_outline
    preExecute: true
    targetted: true
    directTarget: true
    scriptName: verbs/buy_artifacts
    aiUses: true
  - id: recruit_two
    icon: ui/icons/unit_action_icon_recruit.png
    name: ui_unit_verbs_recruit
    targetColour: target
    targetOutlineColour: target_outline
    preExecute: true
    scriptName: verbs/recruit_two
  - id: recruit_two_phase_two
    icon: ui/icons/unit_action_icon_train.png
    name: ui_unit_verbs_train
    targetColour: target
    targetOutlineColour: target_outline
    preExecute: true
    scriptName: verbs/recruit_two_phase_two
    aiUses: true
  - id: cancel_recruit
    icon: ui/icons/unit_action_icon_cancel.png
    name: ui_unit_verbs_cancel_recruit
    scriptName: verbs/cancel_recruit
    targetted: false
  - id: mine
    icon: ui/icons/unit_action_icon_mine.png
    name: ui_unit_verbs_mine
    targetColour: target
    targetOutlineColour: target_outline
    scriptName: verbs/mine
    targetted: true
    directTarget: true
    aiUses: true
  - id: spell_heal
    icon: ui/icons/grooves/unit_action_icon_heal2.png
    name: ui_unit_verbs_spell_heal
    targetColour: target
    targetOutlineColour: target_outline
    scriptName: verbs/spell_heal
    targetted: true
    hasResourceCost: false
  - id: recruit
    icon: ui/icons/unit_action_icon_recruit.png
    name: ui_unit_verbs_recruit
    targetColour: target
    targetOutlineColour: target_outline
    targetted: true
    scriptName: verbs/recruit
  - id: repair
    preExecute: false
    icon: ui/icons/unit_action_icon_build.png
    name: ui_unit_verbs_repair
    scriptName: verbs/repair
    hasResourceCost: false
    targetted: true
    directTarget: true
    targetColour: target
    targetOutlineColour: target_outline
  - id: tech_up
    icon: ui/icons/unit_action_icon_tech_up.png
    name: ui_unit_verbs_tech_up
    scriptName: verbs/tech_up
    targetted: false
    hasResourceCost: true
  - id: pick_up
    icon: ui/icons/unit_action_icon_load.png
    name: ui_unit_verbs_pick_up
    targetColour: target
    targetOutlineColour: target_outline
    targetted: true
    directTarget: true
    scriptName: verbs/pick_up
  - id: drink_h_pot
    icon: ui/icons/unit_action_icon_drink_pot.png
    name: ui_unit_verbs_drink_h_pot
    scriptName: verbs/drink_h_pot
    targetted: false
    aiUses: true
  - id: drink_g_pot
    icon: ui/icons/unit_action_icon_drink_pot.png
    name: ui_unit_verbs_drink_g_pot
    scriptName: verbs/drink_g_pot
    targetted: false
    aiUses: true
  - id: dimensional_door
    icon: ui/icons/unit_action_icon_dimensional_door.png
    name: ui_unit_verbs_dimensional_door
    targetColour: target
    targetOutlineColour: target_outline
    scriptName: verbs/dimensional_door
    targetted: true
    directTarget: true
    aiUses: true
  - id: groove_dummy
    icon: ui/icons/grooves/unit_action_icon_inspire.png
    name: groove_name_dummy
    targetColour: target
    targetted: true                                     # This verb targets some position on the map
    scriptName: verbs/groove_dummy            # The Lua script to run when this verb is used
    aiUses: false
  - id: unload_two
    icon: ui/icons/unit_action_icon_drop.png
    name: ui_unit_verbs_unload
    preExecute: true
    scriptName: verbs/unload_two
    targetColour: target
    targetDisplayColour: attack_target
    targetDisplayOutlineColour: attack_target_outline
    targetOutlineColour: target_outline
    aiUses: true
  - id: wait_villager
    icon: ui/icons/unit_action_icon_wait.png
    name: ui_unit_verbs_wait
    targetColour: target
    targetOutlineColour: target_outline
    scriptName: verbs/wait_villager
    targetted: false
    aiUses: true
...